### PR TITLE
ensure git pushed function - code props to @fgarcia

### LINKED ISSUE #295: Git helper for pending push
I believe that some type of warning or error message when trying to deploy with pending commits would be a sane default.

I use this little helper that prevents my most frequent deployment problem. I leave to the maintainers deciding if this is useful and if it should be a default or a helper function.

    def no_push_pending!
      pending = system "[ $(git log origin/master..master | wc -l) -ne 0 ]"
      fail "Pending git push!" if pending
    end

    desc "Deploys the current version to the server."
    task :deploy => :environment do
      no_push_pending!
      deploy do
        invoke :'git:clone'
        invoke :'deploy:link_shared_paths'
        ....
      end
    end

Obviously the current helper is limited because it only considers the 'master' branch.

### PR DESCRIPTION
**Pull request by devvmh**
Fixes #295 by stealing the code

I don't think this code is ideal as-is. In particular, I'm not 100% sure where the helper should live, and I don't know if it should be included in the default deploy script.

Also, if there is a way to move it from the main deploy task to a before hook, that would be ideal, but I haven't gotten mina 1.x working yet myself so I'm not sure how before hooks work.

### CODE REVIEW

File: lib/mina/dsl.rb [hunk 1]
```diff
@@ -15,6 +15,15 @@ def invoke(task, *args)
       Rake::Task[task].reenable
     end
 
+    def ensure_git_pushed!(opts = {})
+      branch = opts[:branch] || fetch(:branch)
```
Comment (d4be4st) [inline lib/mina/dsl.rb]: `fetch` methoda has a second, default argument. so you can write `fetch(:branch, opts[:branch])`

**Comment by d4be4st** [comment]
This is an often requested feature, but i am not sure if I want to enforce it upon users.

Will test it locally and see if it slows down the deploy significantly. If yes, then maybe just add the command as a comment in data/deploy.rb, if no then happily adding it.

File: lib/mina/dsl.rb (hunk 1 above)
Comment (devvmh) [inline lib/mina/dsl.rb]: Interesting. I was actually thinking of it the other way around - if you write `ensure_git_pushed!` it will do what you expect, and if you have special needs you can specify opts[:branch] or opts[:remote] to override the defaults. Does that sound right?

**Comment by devvmh** [comment]
Yeah, I agree. It shouldn't be the default. I'll change ensure_git_pushed! to a comment in a few hours

**Comment by devvmh** [comment]
I rebased and changed ensure git pushed to be in a comment. What else can I do to make it better? I'm happy to change whatever

**Comment by d4be4st** [comment]
I moved this to a git task as it is using 'git'.

Thank you for the idea!
